version: '3.8'

services:
  dev-crimesocial-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: crimesocial
    networks:
      - firstnetwork
  test-crimesocial-db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: crimesocial
    networks:
      - firstnetwork

networks:
  firstnetwork: